version: '3.8'

services:
  python-tests:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./selecao_simultanea_python:/app
    working_dir: /app
    networks:
      - test-network

  rust-tests:
    build:
      context: .
      dockerfile: Dockerfile.rust
    volumes:
      - ./selecao_simultanea_rust:/app
    working_dir: /app
    networks:
      - test-network

networks:
  test-network:
    driver: bridge